// @ts-nocheck
/*
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
*/

import Head from "next/head";
import Footer from "./sections/footer";
import Header from "./sections/header";
import Stake from "./stake";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quantum Finance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="py-10">
        <Stake />
      </main>
      <Footer />
    </>
  );
}
